---
driver:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  #always_update_cookbooks: true

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7.5

suites:
  - name: default
    run_list:
      - recipe[jenkins_wrapper::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
